Repository ROCm/rocDecode, pull requests merged in 2024-11, with the labels that each got.

#444 Fix exit code for rocDecode-setup.py
  rocDecode-setup.py
Labels: bugfix, ci:precheckin

#448 GPU Arch Updates
  docs/install/install.rst
  samples/videoDecodeRGB/CMakeLists.txt
  src/rocdecode/roc_decoder_caps.h
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
Labels: enhancement, bugfix, ci:precheckin

#426 Fix link
  api/rocdecode.h
Labels: ci:docs-only

#445 made changes to installation and landing pages
  docs/index.rst
  docs/install/quick-start.rst
  docs/install/rocDecode-build-and-install.rst
  docs/install/rocDecode-package-install.rst
  docs/install/rocDecode-prerequisites.rst
  docs/reference/rocDecode-formats-and-architectures.rst
  docs/reference/rocDecode-tested-configurations.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/rocDecode-samples.rst
  docs/what-is-rocDecode.rst
Labels: documentation, ci:docs-only

#451 Removed install.rst since it's been replaced.
  docs/install/install.rst
Labels: documentation, ci:docs-only

#452 HEVC: Added empty NAL detection.
  src/parser/hevc_parser.cpp
  src/parser/roc_video_parser.cpp
Labels: ci:precheckin

#453 ROCm 6.3 Cherry-pick - GPU Arch Updates (#448)
  samples/videoDecodeRGB/CMakeLists.txt
Labels: enhancement

#454 SLES - Updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  api/rocdecode_version.h
  docs/install/rocDecode-prerequisites.rst
  rocDecode-setup.py
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#459 reverted readme
  README.md
Labels: bugfix
