Repository ROCm/rocDecode, pull requests merged in 2024-12, with the labels that each got.

#467 Revert "Samples: Compiler - set CXX Compiler if not set"
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
Labels: bugfix

#468 Samples & Test - Compiler Updates
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#461 ffmpeg software decoder implementation
  CHANGELOG.md
  CMakeLists.txt
  api/rocdecode.h
  samples/videoDecode/CMakeLists.txt
  samples/videoDecode/videodecode.cpp
  utils/ffmpegvideodecode/ffmpeg_video_dec.cpp
  utils/ffmpegvideodecode/ffmpeg_video_dec.h
  utils/rocvideodecode/roc_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.h
Labels: enhancement, ci:precheckin

#474 Added install refactoring
  docs/index.rst
  docs/install/install.rst
  docs/install/quick-start.rst
  docs/install/rocDecode-build-and-install.rst
  docs/install/rocDecode-package-install.rst
  docs/install/rocDecode-prerequisites.rst
  docs/reference/rocDecode-formats-and-architectures.rst
  docs/reference/rocDecode-tested-configurations.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/rocDecode-samples.rst
  docs/what-is-rocDecode.rst
Labels: documentation, ci:docs-only

#465 Create surfaces with linear modifier
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.h
Labels: ci:precheckin

#469 Enable the CMake ROCDECODE_ROCPROFILER_REGISTER option by default
  CMakeLists.txt
Labels: ci:precheckin

#481 Add support for mapping GPU UUIDs to render nodes
  src/rocdecode/roc_decoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.h
Labels: ci:precheckin
