Repository ROCm/rocDecode, pull requests merged in 2024-07, with the labels that each got.

#381 Update formatting in changelog
  CHANGELOG.md
Labels: documentation, ci:docs-only

#382 Update doc requirements and changelog formatting
  CHANGELOG.md
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#380 Update formatting in changelog
  CHANGELOG.md
Labels: documentation, ci:docs-only

#379 CMakeLists - Use -D AMDGPU_TARGETS
  CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
Labels: enhancement

#402 FFMPEG - Multiversion support
  samples/videoDecodeBatch/CMakeLists.txt
Labels: bugfix
