Repository ROCm/rocDecode, pull requests merged in 2024-09, with the labels that each got.

#418 Update Doxyfile to strip Read the Docs dir
  docs/doxygen/Doxyfile
Labels: documentation, ci:docs-only

#414 Simplified MD5 string compare code and fixed potential incorrect conversion of MD5 string to integers.
  samples/videoDecode/videodecode.cpp
  samples/videoDecodeMem/videodecodemem.cpp
  samples/videoDecodeRGB/videodecrgb.cpp
  test/testScripts/run_rocDecodeSamples.py
Labels: ci:precheckin

#423 Support GFX12
  samples/videoDecodeRGB/CMakeLists.txt
  src/rocdecode/roc_decoder_caps.h
Labels: enhancement, bugfix, ci:precheckin

#417 Added a note pointing users to the official documentation and removed…
  README.md
Labels: ci:docs-only
