Repository ROCm/rocDecode, pull requests merged in 2024-10, with the labels that each got.

#427 change clang++ path as suggested by packaging team
  CMakeLists.txt
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
Labels: bugfix, ci:precheckin

#428 Find rocDecode - Support added
  cmake/FindrocDecode.cmake
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, ci:precheckin

#416 Package - dependencies updated
  CHANGELOG.md
  CMakeLists.txt
  README.md
  api/rocdecode_version.h
  docs/install/install.rst
  rocDecode-setup.py
Labels: enhancement, bugfix, ci:precheckin

#430 Add new API rocDecParserMarkFrameForReuse() for Parser
  CHANGELOG.md
  api/rocparser.h
  src/parser/parser_handle.h
  src/parser/roc_video_parser.cpp
  src/parser/roc_video_parser.h
  src/parser/rocparser_api.cpp
  src/rocdecode/roc_decoder.cpp
  src/rocdecode/roc_decoder.h
Labels: enhancement, ci:precheckin

#435 Fix libva requirements for rocdecode
  CHANGELOG.md
  CMakeLists.txt
  README.md
  rocDecode-setup.py
Labels: ci:precheckin
