Repository ROCm/rocDecode, pull requests merged in 2024-06, with the labels that each got.

#361 Docs: reordered index grid (#345)
  docs/index.rst
  docs/install/install.rst
  docs/install/quick-start.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/README.md
Labels: ci:docs-only

#368 Mariner - Support for package
  CMakeLists.txt
Labels: enhancement, bugfix

#369 Setup - mariner build support
  CHANGELOG.md
  README.md
  rocDecode-setup.py
Labels: enhancement
