Repository ROCm/rocDecode, pull requests merged in 2025-03, with the labels that each got.

#523 CTest: Added CTest for VP9 decode on bitstream reader.
  CHANGELOG.md
  test/CMakeLists.txt
Labels: ci:precheckin

#526 Added syntax error handling in VPS parsing.
  CHANGELOG.md
  src/parser/hevc_parser.cpp
  src/parser/hevc_parser.h
  src/parser/roc_video_parser.h
Labels: ci:precheckin

#511 added howto use for the utility classes
  docs/conceptual/rocDecode-memory-types.rst
  docs/how-to/using-rocDecode-ffmpeg.rst
  docs/how-to/using-rocDecode-video-decoder.rst
  docs/how-to/using-rocDecode-videodecode-sample.rst
  docs/how-to/using-rocdecode.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/rocDecode-samples.rst
  docs/what-is-rocDecode.rst
Labels: documentation, ci:docs-only

#529 HEVC error resilience: Fixed a vulnerability with active PPS id.
  src/parser/hevc_parser.cpp
Labels: ci:precheckin

#527 HEVC: Added bit depth change support in decoder reconfiguration.
  CHANGELOG.md
  CMakeLists.txt
  api/rocdecode.h
  api/rocdecode_version.h
  src/parser/hevc_parser.cpp
  src/parser/roc_video_parser.cpp
  src/parser/roc_video_parser.h
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  utils/ffmpegvideodecode/ffmpeg_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.h
Labels: ci:precheckin

#530 Remove unused VA_CHECK_VERSION
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
Labels: ci:precheckin

#535 Bug fix required for rocal
  api/rocdecode_version.h.in
Labels: enhancement, ci:precheckin

#531 HEVC: Added DPB size change handling through decoder reconfiguration.
  CHANGELOG.md
  src/parser/hevc_parser.cpp
  src/parser/roc_video_parser.cpp
  src/rocdecode/roc_decoder.cpp
  utils/rocvideodecode/roc_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.h
Labels: enhancement, ci:precheckin

#539 adding some bitstream reader api doc
  docs/how-to/using-rocDecode-bitstream.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#542 HEVC Error resilience: Added invalid syntax detection in SPS, PPS, and slice header parsing.
  api/rocdecode/rocdecode.h
  src/parser/hevc_defines.h
  src/parser/hevc_parser.cpp
  src/parser/hevc_parser.h
Labels: ci:precheckin

#547 HEVC error resilience: Added dependant slice error handling.
  src/parser/hevc_defines.h
  src/parser/hevc_parser.cpp
Labels: ci:precheckin

#544 Script: Added the decode status check mode to the rocDecode samples script.
  test/testScripts/run_rocDecodeSamples.py
Labels: ci:precheckin

#548 HEVC error resilience: Adjusted the range check for the total reference picture number so more errors can be detected.
  src/parser/avc_parser.cpp
  src/parser/hevc_parser.cpp
Labels: ci:precheckin
