Repository ROCm/rocDecode, pull requests merged in 2025-10, with the labels that each got.

#658 Packaging - Remove Meta Package dependency
  CMakeLists.txt
  README.md
  rocDecode-setup.py
Labels: enhancement, bugfix, ci:precheckin

#659 changelog update for PR658
  CHANGELOG.md
Labels: ci:docs-only

#662 ROCm 7.1 - Changelog updates
  CHANGELOG.md
Labels: documentation, enhancement, bugfix, ci:docs-only

#664 Compiler - Location update
  CMakeLists.txt
  samples/rocdecDecode/CMakeLists.txt
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodePicFiles/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoDecodeRaw/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
  src/rocdecode-host/CMakeLists.txt
  test/CMakeLists.txt
  test/rocDecodeNegativeApiTests/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin
