Repository ROCm/rocDecode, pull requests merged in 2025-09, with the labels that each got.

#646 FFmpeg version support for 5.1 and 6.1
  src/rocdecode-host/CMakeLists.txt
  src/rocdecode-host/avcodec/avcodec_videodecoder.cpp
  src/rocdecode-host/avcodec/avcodec_videodecoder.h
Labels: bugfix, ci:precheckin

#650 Find package - rocdecode-host
  CMakeLists.txt
  api/rocdecode-host_version.h.in
  cmake_modules/rocdecode-host-config.cmake.in
  samples/rocdecDecode/CMakeLists.txt
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  src/rocdecode-host/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#654 Cherry pick OS wording changes
  README.md
  docs/index.rst
  docs/install/rocDecode-prerequisites.rst
Labels: documentation, ci:docs-only

#653 removing SP6
  README.md
  docs/install/rocDecode-prerequisites.rst
Labels: documentation, ci:docs-only

#656 Drop libva-amdgpu for RHEL 9+ and SLE
  CMakeLists.txt
  cmake/FindLibva.cmake
  rocDecode-setup.py
Labels: enhancement, ci:precheckin
