Repository ROCm/rocDecode, pull requests merged in 2025-04, with the labels that each got.

#546 CMakeLists - Set Std updates
  .jenkins/common.groovy
  CMakeLists.txt
  samples/videoDecode/CMakeLists.txt
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodePicFiles/CMakeLists.txt
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoDecodeRaw/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin

#549 AVC error resilience: Added bitstream syntax error handling.
  CHANGELOG.md
  src/parser/avc_defines.h
  src/parser/avc_parser.cpp
  src/parser/avc_parser.h
Labels: ci:precheckin

#550 AVC: Fixed an issue in video size change cases, where the remaining decoded buffers of the previous video size in DPB are not output.
  src/parser/avc_parser.cpp
Labels: ci:precheckin

#551 CI update - Add avc, av1 and vp9 conformance to CI
  .jenkins/common.groovy
Labels: enhancement, ci:precheckin

#552 Code Clean up - remove unused API
  api/rocdecode/rocparser.h
  src/parser/parser_handle.h
  src/parser/roc_video_parser.cpp
  src/parser/roc_video_parser.h
  src/parser/rocparser_api.cpp
Labels: enhancement, ci:precheckin

#553 AVC: Added support for in stream DPB buffer size change.
  CHANGELOG.md
  src/parser/avc_parser.cpp
  utils/rocvideodecode/roc_video_dec.cpp
Labels: ci:precheckin

#556 Code Coverage - Updates
  .jenkins/common.groovy
Labels: enhancement, ci:precheckin

#558 Add extra error checking during decoder reconfiguration
  src/rocdecode/roc_decoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
Labels: ci:precheckin

#560 close the drm_fd in the VaContext destructor
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.h
Labels: ci:precheckin

#562 CTest: Add a test to perform negative testing on all rocDecode APIs
  CMakeLists.txt
  test/CMakeLists.txt
  test/rocDecodeNegativeApiTests/CMakeLists.txt
  test/rocDecodeNegativeApiTests/README.md
  test/rocDecodeNegativeApiTests/rocdecode_api_negative_tests.cpp
  test/rocDecodeNegativeApiTests/rocdecode_api_negative_tests.h
  test/rocDecodeNegativeApiTests/rocdecodenegativetest.cpp
Labels: ci:precheckin

#564 code cleanup - fix a typo
  test/rocDecodeNegativeApiTests/rocdecode_api_negative_tests.cpp
Labels: ci:precheckin

#568 Update .codecov.yaml
  .codecov.yaml
Labels: enhancement

#567 Change Jenkins CI behavior to be more efficient
  .jenkins/common.groovy
Labels: ci:precheckin

#572 CI: Added AVC and HEVC decode stability tests to CI.
  .jenkins/common.groovy
  test/testScripts/run_rocDecodeSamples.py
Labels: ci:precheckin

#573 CI: Do not do AV1 conformance test on MI2xx or MI1xx, which does not support AV1 decode.
  .jenkins/common.groovy
Labels: ci:precheckin

#576 CI: Added AV1 stability test to CI.
  .jenkins/common.groovy
  test/testScripts/run_rocDecodeSamples.py
Labels: enhancement, ci:precheckin

#574 Decoder utility: Removed a couple of incorrect asserts.
  CHANGELOG.md
  CMakeLists.txt
  utils/rocvideodecode/roc_video_dec.h
Labels: bugfix, ci:precheckin
