Repository ROCm/rocDecode, pull requests merged in 2025-02, with the labels that each got.

#505 gfx update
  samples/videoDecodeRGB/CMakeLists.txt
Labels: ci:precheckin

#508 VP9: Added support for video size change (scaling down) on inter frames.
  api/rocparser.h
  src/parser/av1_parser.cpp
  src/parser/avc_parser.cpp
  src/parser/hevc_parser.cpp
  src/parser/vp9_parser.cpp
  src/parser/vp9_parser.h
  utils/rocvideodecode/roc_video_dec.cpp
Labels: ci:precheckin

#510 rename some macros so it doesn't clash with others
  samples/videoDecode/videodecode.cpp
  samples/videoDecodeBatch/videodecodebatch.cpp
  samples/videoDecodePerf/videodecodeperf.cpp
  samples/videoToSequence/videotosequence.cpp
  utils/ffmpegvideodecode/ffmpeg_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.h
Labels: enhancement, ci:precheckin

#512 Optimization: Reduced decode session start latency for certain output surface memory types.
  CHANGELOG.md
  samples/videoDecodeRGB/videodecrgb.cpp
  utils/rocvideodecode/roc_video_dec.cpp
  utils/rocvideodecode/roc_video_dec.h
Labels: ci:precheckin

#515 made changes to installation and landing pages (#445)
  docs/index.rst
  docs/install/quick-start.rst
  docs/install/rocDecode-build-and-install.rst
  docs/install/rocDecode-package-install.rst
  docs/install/rocDecode-prerequisites.rst
  docs/reference/rocDecode-formats-and-architectures.rst
  docs/reference/rocDecode-tested-configurations.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/rocDecode-samples.rst
  docs/what-is-rocDecode.rst
Labels: documentation, ci:docs-only

#514 Bug fix - videoToSequence sample
  samples/common.h
  samples/videoToSequence/videotosequence.cpp
Labels: ci:precheckin

#516 Update rocm-docs-core version
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#513 Check ROCm targets
  samples/videoDecodeRGB/CMakeLists.txt
Labels: ci:precheckin

#518 [Samples] - fix the issue of out-of-order processing in the videoDecodeRGB sample
  samples/videoDecodeRGB/videodecrgb.cpp
Labels: ci:precheckin

#521 VideoSeekContext - Introduce requested frame pts
  utils/video_demuxer.h
Labels: ci:precheckin

#519 VP9: Added VP9 IVF container detection and picture data parsing support to bitstream reader.
  CHANGELOG.md
  CMakeLists.txt
  api/rocdecode_version.h
  src/bit_stream_reader/es_reader.cpp
  src/bit_stream_reader/es_reader.h
Labels: ci:precheckin
