Repository ROCm/rocDecode, pull requests merged in 2025-01, with the labels that each got.

#483 CMakeLists - Updates and cleanup
  CHANGELOG.md
  CMakeLists.txt
  README.md
  rocDecode-setup.py
  samples/videoDecode/CMakeLists.txt
  samples/videoDecode/README.md
  samples/videoDecodeBatch/CMakeLists.txt
  samples/videoDecodeBatch/README.md
  samples/videoDecodeMem/CMakeLists.txt
  samples/videoDecodeMem/README.md
  samples/videoDecodeMultiFiles/CMakeLists.txt
  samples/videoDecodeMultiFiles/README.md
  samples/videoDecodePerf/CMakeLists.txt
  samples/videoDecodePerf/README.md
  samples/videoDecodeRGB/CMakeLists.txt
  samples/videoDecodeRGB/README.md
  samples/videoDecodeRaw/CMakeLists.txt
  samples/videoToSequence/CMakeLists.txt
  samples/videoToSequence/README.md
  test/CMakeLists.txt
  test/testScripts/README.md
Labels: enhancement, bugfix, ci:precheckin

#487 VP9: Fixed issues with filter parameters.
  src/parser/vp9_parser.cpp
Labels: ci:precheckin

#488 VP9: Increased DPB buffer size to handle streams with the maximum number of the reference frames allowed.
  src/parser/vp9_defines.h
  src/parser/vp9_parser.cpp
  src/parser/vp9_parser.h
Labels: ci:precheckin

#489 fix for build errors with FFMpeg version 6
  utils/ffmpegvideodecode/ffmpeg_video_dec.cpp
  utils/ffmpegvideodecode/ffmpeg_video_dec.h
Labels: ci:precheckin

#479 Support to obtain dts from demuxer and seek
  utils/video_demuxer.h
Labels: ci:precheckin

#415 Added the new GPU VA context class to handle VA connections to GPU. Removed the hard coded HW decoder capability info.
  src/rocdecode/roc_decoder.cpp
  src/rocdecode/roc_decoder.h
  src/rocdecode/roc_decoder_caps.h
  src/rocdecode/rocdecode_api.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.h
  utils/rocvideodecode/roc_video_dec.cpp
Labels: bugfix, ci:precheckin

#492 code cleanup - remove unnecessary check
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
Labels: ci:precheckin

#493 Optimize finding the compute partition mode
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.h
Labels: ci:precheckin

#496 Create separate VA display for each decoder instance.
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
Labels: ci:precheckin

#497 Eliminate the use of std::fs
  CMakeLists.txt
  src/rocdecode/vaapi/vaapi_videodecoder.cpp
  src/rocdecode/vaapi/vaapi_videodecoder.h
Labels: ci:precheckin

#499 Readme - Updates
  README.md
Labels: enhancement, ci:docs-only

#500 Setup - Install ffmpeg-devel on RHEL 9
  rocDecode-setup.py
Labels: enhancement, bugfix, ci:precheckin

#501 fix for build errors in ubuntu24.04
  utils/ffmpegvideodecode/ffmpeg_video_dec.h
Labels: bugfix, ci:precheckin

#502 Cherry pick doc changes into 6.3.2
  docs/index.rst
  docs/install/install.rst
  docs/install/quick-start.rst
  docs/install/rocDecode-build-and-install.rst
  docs/install/rocDecode-package-install.rst
  docs/install/rocDecode-prerequisites.rst
  docs/reference/rocDecode-formats-and-architectures.rst
  docs/reference/rocDecode-tested-configurations.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/rocDecode-samples.rst
  docs/what-is-rocDecode.rst
Labels: documentation, ci:docs-only
